### PR TITLE
Refine estimate of bytes needed to write a TIFF plane

### LINKED ISSUE #4113: TiffWriter: incorrect BigTIFF threshold
Issue was raised on forum thread https://forum.image.sc/t/possible-bio-formats-bfconvert-bigtiff-threshold-bug/88042

The user reported an exception when attempting to write 8 planes each of 429.9 Mb so a total data size of 3.44Gb. An exception is then thrown from the TiffWriter as it checks if there is enough space for 2 full planes from the end of the output stream:
https://github.com/ome/bioformats/blob/e484e1faefd6c7590fa5dbb56e56f3cc360d9139/components/formats-bsd/src/loci/formats/out/TiffWriter.java#L381-L387

I was able to reproduce locally by writing an uncompressed file of size 12000 * 20000 * 2 * 8. If I manually override the check then a valid TIFF file is written under the threshold size and validates with tiffinfo.

### PR DESCRIPTION
**Pull request by melissalinkert**
Fixes #4113.

Instead of just doubling the number of pixel bytes, estimate the number of bytes needed to write the corresponding IFD. As a consequence, this adds methods to get the number of bytes needed to write an IFD and the IFDType for a particular value.

The test case in #4113 should now successfully convert without exception:

```bfconvert "test&sizeX=12000&sizeY=20000&sizeZ=8&sizeT=2.fake" test.tiff```

and the resulting file should be less than 4GB and readable as expected. Increasing the plane count in the test case should continue to throw an exception indicating that BigTIFF is required (but this is expected).

Given that this adds some new API to the TIFF classes and 8.4.0 is rapidly approaching, I'd be OK with pushing this PR to the next milestone if more time to review/discuss would be helpful.

### CODE REVIEW

**Review by sbesson — CHANGES_REQUESTED** [review]
While testing this PR, part of the issue is that the ImageConverter call calls `setId` on the file before setting the compression via `setCompression`. For TIFF based format, the logic in `TiffWriter.setId` will automatically switch to BigTIFF is the pixel byte count exceeds 4.2GB. 

I reproduced the current behavior using:
- Bio-Formats 8.4.0 `bfconvert` with no compression option
- a variant of the image dimensions from the original issue with a single channel and varying sizeZ to have finer control of the total byte count
- for image dimensions exceeding 4.2GB, the conversion command was repeated using `-nobigtiff` to turn off the automatic switch to BigTIFF

| Source                                     | Option     | BigTIFF ? | Success | File Size  |
|--------------------------------------------|------------|-----------|---------|------------|
| test&sizeX=12000&sizeY=20000&sizeZ=14.fake |            | no        | yes     | 3360032376 |
| test&sizeX=12000&sizeY=20000&sizeZ=15.fake |            | no        | yes     | 3600034688 |
| test&sizeX=12000&sizeY=20000&sizeZ=16.fake |            | no        | no      |            |
| test&sizeX=12000&sizeY=20000&sizeZ=17.fake |            | no        | no      |            |
| test&sizeX=12000&sizeY=20000&sizeZ=18.fake |            | yes       | yes     | 4320079954 |
| test&sizeX=12000&sizeY=20000&sizeZ=18.fake | -nobigtiff | no        | no      |            |
| test&sizeX=12000&sizeY=20000&sizeZ=19.fake |            | yes       | yes     | 4560084414 |
| test&sizeX=12000&sizeY=20000&sizeZ=19.fake | -nobigtiff | no        | no      |            |

In summary
- the conversion works when the input dimensions are either small or large (with the automatic BigTIFF switch)
- the conversion fails with large input dimension and no switch to BigTIFF - this is never expected to work and the conversion command prints a warning message explaining that the pixel byte count is larger than 4.2GB
- the conversion fails for a range of input dimensions resulting in file sizes just below 4.2GB

With this PR included, the same commands yields the following results

| Source                                     | Option     | BigTIFF ? | Success | File Size  |
|--------------------------------------------|------------|-----------|---------|------------|
| test&sizeX=12000&sizeY=20000&sizeZ=14.fake |            | no        | yes     | 3360032502 |
| test&sizeX=12000&sizeY=20000&sizeZ=15.fake |            | no        | yes     | 3600034823 |
| test&sizeX=12000&sizeY=20000&sizeZ=16.fake |            | no        | yes     | 3840037144 |
| test&sizeX=12000&sizeY=20000&sizeZ=17.fake |            | no        | no      |            |
| test&sizeX=12000&sizeY=20000&sizeZ=18.fake |            | yes       | yes     | 4320080134 |
| test&sizeX=12000&sizeY=20000&sizeZ=18.fake | -nobigtiff | no        | no      |            |
| test&sizeX=12000&sizeY=20000&sizeZ=19.fake |            | yes       | yes     | 4560084585 |
| test&sizeX=12000&sizeY=20000&sizeZ=19.fake | -nobigtiff | no        | no      |            |

While `test&sizeX=12000&sizeY=20000&sizeZ=16.fake` now converts as expected, `test&sizeX=12000&sizeY=20000&sizeZ=17.fake` which is still below the 4.2GB limit fails with the `File is too large; call setBigTiff(true)` error but the file size is still 4055079465 bytes. Is there still a small overestimation of the position for the last IFD offset?

**Comment by melissalinkert** [comment]
With fd4a2fd, the max number of pixel byte to be written is calculated based on the tile size instead of the plane size. That should allow `test&sizeX=12000&sizeY=20000&sizeZ=17.fake` to convert without error.

File: components/formats-bsd/test/loci/formats/utests/out/TiffWriterTest.java [hunk 1]
```diff
@@ -135,16 +135,15 @@ public void tearDown() throws Exception {
 
   @Test
   public void testSetBigTiffFileTooLarge() throws IOException, FormatException {
-    // Test that no exception is thrown while below the big tiff limit (2147483648L)
-    // Exception is thrown when size is out.length() + 2 * (width * height * c * bytesPerPixel)
+    // Test that no exception is thrown while below the big tiff limit (4294967296L)
     writer.setMetadataRetrieve(metadata);
     ((TiffWriterMock)writer).createOutputBuffer(true);
-    long length = 4294967296L - (buf.length * 4);
+    long length = 4294967296L - (buf.length * 2);
```
Comment (sbesson) [inline components/formats-bsd/test/loci/formats/utests/out/TiffWriterTest.java:141]: Incidentally this change makes the test directly comparable to `testSetBigTiff` which uses the same initial offset with `setBigTiff(true)`

For maximal parity, could `testSetBigTiff` be updated to also execute `writer.saveBytes(1, buf, ifd);`?

**Review by sbesson — CHANGES_REQUESTED** [review]
Retested the various conversion scenarios including tiled writing for the different input dimensions

| Source                                     | Option                  | Success | BigTIFF ? | File Size  |
|--------------------------------------------|-------------------------|---------|-----------|------------|
| test&sizeX=12000&sizeY=20000&sizeZ=14.fake |                         | yes     | no        | 3360032502 |
| test&sizeX=12000&sizeY=20000&sizeZ=14.fake | -tilex 1024 -tiley 1024 | yes     | no        | 3523246742 |
| test&sizeX=12000&sizeY=20000&sizeZ=15.fake |                         | yes     | no        | 3600034823 |
| test&sizeX=12000&sizeY=20000&sizeZ=15.fake | -tilex 1024 -tiley 1024 | yes     | no        | 3774907223 |
| test&sizeX=12000&sizeY=20000&sizeZ=16.fake |                         | yes     | no        | 3840037144 |
| test&sizeX=12000&sizeY=20000&sizeZ=16.fake | -tilex 1024 -tiley 1024 | yes     | no        | 4026567704 |
| test&sizeX=12000&sizeY=20000&sizeZ=17.fake |                         | yes     | no        | 4080039465 |
| test&sizeX=12000&sizeY=20000&sizeZ=17.fake | -tilex 1024 -tiley 1024 | yes     | no        | 4278228185 |
| test&sizeX=12000&sizeY=20000&sizeZ=18.fake |                         | yes     | yes       | 4320080134 |
| test&sizeX=12000&sizeY=20000&sizeZ=18.fake | -tilex 1024 -tiley 1024 | yes     | yes       | 4529925574 |
| test&sizeX=12000&sizeY=20000&sizeZ=18.fake | -nobigtiff              | no      | n/a       | n/a        |
| test&sizeX=12000&sizeY=20000&sizeZ=19.fake |                         | yes     | yes       | 4560084585 |
| test&sizeX=12000&sizeY=20000&sizeZ=19.fake | -tilex 1024 -tiley 1024 | yes     | yes       | 4781588105 |
| test&sizeX=12000&sizeY=20000&sizeZ=19.fake | -nobigtiff              | no      | n/a       | n/a        |

The outcome of the utility is consistent with the expectations of the API. Just one suggestion on the unit tests and this should be good to go

File: components/formats-bsd/test/loci/formats/utests/out/TiffWriterTest.java (hunk 1 above)
Comment (melissalinkert) [reply components/formats-bsd/test/loci/formats/utests/out/TiffWriterTest.java:141]: Done in d00a3c05f0.

**Review by sbesson — APPROVED** [review]

**Comment by ian5432** [comment]
Thanks for doing this guys.  I guess that will be my last interaction with OME.
