### PR TITLE
CZI: Detector fixes

### LINKED ISSUE #3501: CZI (from AiryScan2) cannot be read in BioFormats 6.3.1
Hi guys,

I tried to open the attached CZI (from AiryScan2) using BioFormats 6.3.1 and got an exception and we think it is releated to entries for the Zoom level like illustrated below. Let me know if you need more info to fix it.

Sebi

image

```
(Fiji Is Just) ImageJ 2.0.0-rc-71/1.52p; Java 1.8.0_172 [64-bit]; Windows 10 10.0; 207MB of 24433MB (<1%)
 
java.lang.NumberFormatException: For input string: "2.8,2.8"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at java.lang.Double.<init>(Double.java:608)
	at loci.formats.in.ZeissCZIReader.translateInformation(ZeissCZIReader.java:2367)
	at loci.formats.in.ZeissCZIReader.translateMetadata(ZeissCZIReader.java:2002)
	at loci.formats.in.ZeissCZIReader.initFile(ZeissCZIReader.java:1131)
	at loci.formats.FormatReader.setId(FormatReader.java:1389)
	at loci.plugins.in.ImportProcess.initializeFile(ImportProcess.java:499)
	at loci.plugins.in.ImportProcess.execute(ImportProcess.java:142)
	at loci.plugins.in.Importer.showDialogs(Importer.java:140)
	at loci.plugins.in.Importer.run(Importer.java:76)
	at loci.plugins.LociImporter.run(LociImporter.java:78)
	at ij.IJ.runUserPlugIn(IJ.java:230)
	at ij.IJ.runPlugIn(IJ.java:193)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at ij.IJ.run(IJ.java:312)
	at ij.IJ.run(IJ.java:323)
	at ij.macro.Functions.doRun(Functions.java:624)
	at ij.macro.Functions.doFunction(Functions.java:97)
	at ij.macro.Interpreter.doStatement(Interpreter.java:275)
	at ij.macro.Interpreter.doStatements(Interpreter.java:261)
	at ij.macro.Interpreter.run(Interpreter.java:157)
	at ij.macro.Interpreter.run(Interpreter.java:91)
	at ij.macro.MacroRunner.run(MacroRunner.java:139)
	at java.lang.Thread.run(Thread.java:748)
```

[Fluocell_Airyscan.zip](https://github.com/ome/bioformats/files/4103448/Fluocell_Airyscan.zip)

### PR DESCRIPTION
**Pull request by dgault**
Fixes #3501

This should fix the issue raised in https://github.com/ome/bioformats/issues/3501
When testing that bug I also noticed that the Detector ID's being used could be more accurate and also that some of the values for a given detector are being copied over to the next even if they dont exist in that later detector. 

A sample file was provided in the GitHub Issue which I will configure before review

### CODE REVIEW

**Comment by dgault** [comment]
Single repo test failure (https://merge-ci.openmicroscopy.org/jenkins/job/BIOFORMATS-test-folder/48224/consoleFull) will be fixed by last config update https://github.com/openmicroscopy/data_repo_config/pull/444/commits/4115b2e96d3bb34ec3a22578a5f36643957230cb

File: components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java [hunk 1]
```diff
@@ -2345,28 +2344,32 @@ else if ("Filament".equals(type)) {
...
-          }
-          if (zoom != null && !zoom.equals("")) {
-            store.setDetectorZoom(new Double(zoom), 0, detectorIndex);
+          zoom = getFirstNodeValue(detector, "Zoom");
+          if (zoom != null && !zoom.isEmpty()) {
+            if (zoom != null && !zoom.equals("")) {
+              if (zoom.indexOf(',') != -1) {
+                zoom = zoom.substring(0, zoom.indexOf(','));
+              }
+              store.setDetectorZoom(new Double(zoom), 0, detectorIndex);
```
Comment (mtbc) [inline components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java]:
```suggestion
              store.setDetectorZoom(DataTools.parseDouble(zoom), 0, detectorIndex);
```

**Comment by dgault** [comment]
Merging as repo tests are now green: https://merge-ci.openmicroscopy.org/jenkins/job/BIOFORMATS-test-folder/48544/consoleFull
